### ISSUE TITLE
PSD problem

### ISSUE THREAD

**Issue by aringler-usgs** [usgs/xmax#1]
Hello Mike,

Here is what we get when we try to do a PSD.

Best,
Adam

Response loaded from file: /APPS/metadata/RESPS/RESP.IU.ANMO.00.LHZ
    SEED units:  In="((METER) (SECOND^-1) )"(vel), Out="COUNT"
    Calc_sens=3.259590E+09 (reported=3.275080E+09) @ 2.000000E-02 Hz
    Calc_delay=1.450000E+01, Correction_applied=1.593000E+01
    Est_delay=1.593000E+01, Final_sample_interval=1.000000E+00(sec/sample)
    Stg  1:  LAPLACE    A0=8.629850E+04    5 Poles    2 Zeros  Sd=1.952100E+03
    Stg  2:  FIR        H0=1.0             0 Coefficients      SInt=1.000000E+00 Sd=1.677720E+06
    Stg  3:  FIR        H0=1.004752E+00   31 Coefficients      SInt=1.000000E+00 Sd=9.952713E-01
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: This dataset already contains a series with the key MODEL
	at org.jfree.data.xy.XYSeriesCollection.addSeries(XYSeriesCollection.java:153)
	at ViewPSD.createDataset(ViewPSD.java:346)
	at ViewPSD.<init>(ViewPSD.java:94)
	at TransPSD.transform(TransPSD.java:42)
	at com.isti.xmax.gui.XMAXframe$PowerSpectraDensityAction.actionPerformed(XMAXframe.java:1883)
	at com.isti.xmax.gui.CommandButton.mouseClicked(CommandButton.java:118)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6392)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3268)
	at java.awt.Component.processEvent(Component.java:6154)
	at java.awt.Container.processEvent(Container.java:2045)
	at java.awt.Component.dispatchEventImpl(Component.java:4750)
	at java.awt.Container.dispatchEventImpl(Container.java:2103)
	at java.awt.Component.dispatchEvent(Component.java:4576)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4633)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4306)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4227)
	at java.awt.Container.dispatchEventImpl(Container.java:2089)
	at java.awt.Window.dispatchEventImpl(Window.java:2518)
	at java.awt.Component.dispatchEvent(Component.java:4576)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:678)
	at java.awt.EventQueue.access$400(EventQueue.java:96)
	at java.awt.EventQueue$2.run(EventQueue.java:637)
	at java.awt.EventQueue$2.run(EventQueue.java:635)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:116)
	at java.awt.EventQueue$3.run(EventQueue.java:651)
	at java.awt.EventQueue$3.run(EventQueue.java:649)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:648)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)

**Comment by jholland-usgs** [comment]
I believe this is no longer an issue. If it is it will be tracked internally.
